#theme: jekyll-theme-slate
#title: Ronaldo G. M. Rodrigues
#description: Página de projetos
# Site wide configuration

title: Academic web site
locale: pt_BR
logo: # filename of a logo image that has been placed into your images directory

# Enter the following platform usernames if you would like for them to appear on your site.
owner:
  name: Ronaldo G. M. Rodrigues
  avatar: photo.jpg
  bio: "Mestre em Física pela UFMG"
  email: #@ohsu.edu
  # Do not include the @ symbol in your Twitter username
  twitter: #laderast
  linkedin: https://www.linkedin.com/in/ronaldo-givisiez/
  github: https://github.com/RGivisiez
  orcid: # ID Number (ex. 0000-0000-0000-0000)
  researchgate: #username
  mendeley: #username
  google:
    plus: #username
    analytics:
    verify:
    scholar: #id
